In [68]:
from transformers import LayoutLMv3Processor, LayoutLMv3ForTokenClassification
import torch 
from paddleocr import PaddleOCR
import paddle
import pprint
import numpy as np


In [20]:
gpu_or_cpu="cuda" if torch.cuda.is_available() else "cpu"
device = torch.device(gpu_or_cpu) #used to set the model to run in cpu or cuda 

print("Using device:", device)

model = LayoutLMv3ForTokenClassification.from_pretrained("microsoft/layoutlmv3-base")
processor = LayoutLMv3Processor.from_pretrained("microsoft/layoutlmv3-base")

# Move model to GPU
model.to(device)

Using device: cuda


Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

LayoutLMv3ForTokenClassification LOAD REPORT from: microsoft/layoutlmv3-base
Key                                | Status     | 
-----------------------------------+------------+-
layoutlmv3.embeddings.position_ids | UNEXPECTED | 
classifier.bias                    | MISSING    | 
classifier.weight                  | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


LayoutLMv3ForTokenClassification(
  (layoutlmv3): LayoutLMv3Model(
    (embeddings): LayoutLMv3TextEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (x_position_embeddings): Embedding(1024, 128)
      (y_position_embeddings): Embedding(1024, 128)
      (h_position_embeddings): Embedding(1024, 128)
      (w_position_embeddings): Embedding(1024, 128)
    )
    (patch_embed): LayoutLMv3PatchEmbeddings(
      (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
    )
    (pos_drop): Dropout(p=0.0, inplace=False)
    (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (norm): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
    (encoder): LayoutLMv3Encoder

In [23]:
image_path = "./training data/1.jpg"

In [52]:
print(paddle.device.get_device())
ocr = PaddleOCR(use_textline_orientation=True, lang='en', device='gpu')
result = ocr.predict(image_path)

Creating model: ('PP-LCNet_x1_0_doc_ori', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Anuj S Jain\.paddlex\official_models\PP-LCNet_x1_0_doc_ori`.


gpu:0


Creating model: ('UVDoc', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Anuj S Jain\.paddlex\official_models\UVDoc`.
Creating model: ('PP-LCNet_x1_0_textline_ori', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Anuj S Jain\.paddlex\official_models\PP-LCNet_x1_0_textline_ori`.
Creating model: ('PP-OCRv5_server_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Anuj S Jain\.paddlex\official_models\PP-OCRv5_server_det`.
Creating model: ('en_PP-OCRv5_mobile_rec', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Anuj S Jain\.paddlex\official_models\en_PP-OCRv5_mobile_rec`.


In [26]:
pprint.pprint(result)

[{'doc_preprocessor_res': {'angle': 0,
                           'input_img': array([[[51, ..., 48],
        ...,
        [39, ..., 49]],

       ...,

       [[30, ..., 46],
        ...,
        [23, ..., 14]]], shape=(3300, 2232, 3), dtype=uint8),
                           'input_path': None,
                           'model_settings': {'use_doc_orientation_classify': True,
                                              'use_doc_unwarping': True},
                           'output_img': array([[[255, ..., 255],
        ...,
        [255, ..., 255]],

       ...,

       [[255, ..., 255],
        ...,
        [255, ..., 255]]], shape=(3300, 2232, 3), dtype=uint8),
                           'page_index': None,
                           'rot_img': array([[[51, ..., 48],
        ...,
        [39, ..., 49]],

       ...,

       [[30, ..., 46],
        ...,
        [23, ..., 14]]], shape=(3300, 2232, 3), dtype=uint8)},
  'dt_polys': [array([[82, 15],
       ...,
       [82, 59]], sha

In [39]:
result

[{'input_path': './training data/1.jpg',
  'page_index': None,
  'doc_preprocessor_res': {'input_path': None,
   'page_index': None,
   'input_img': array([[[51, ..., 48],
           ...,
           [39, ..., 49]],
   
          ...,
   
          [[30, ..., 46],
           ...,
           [23, ..., 14]]], shape=(3300, 2232, 3), dtype=uint8),
   'model_settings': {'use_doc_orientation_classify': True,
    'use_doc_unwarping': True},
   'angle': 0,
   'rot_img': array([[[51, ..., 48],
           ...,
           [39, ..., 49]],
   
          ...,
   
          [[30, ..., 46],
           ...,
           [23, ..., 14]]], shape=(3300, 2232, 3), dtype=uint8),
   'output_img': array([[[255, ..., 255],
           ...,
           [255, ..., 255]],
   
          ...,
   
          [[255, ..., 255],
           ...,
           [255, ..., 255]]], shape=(3300, 2232, 3), dtype=uint8)},
  'dt_polys': [array([[82, 15],
          ...,
          [82, 59]], shape=(4, 2), dtype=int16),
   array([[1264,   1

In [40]:
pprint.pprint(len(result[0]["rec_texts"]))
pprint.pprint(result[0]["rec_texts"])

147
['PARMESHWARA STATIONERY',
 'Involce No.',
 'e-Way Bill No.',
 'Dated',
 'Near Hasanamba Temple Circle, Balegara Street',
 'PS/25-26/1712',
 '18-Sep-26',
 'Delivery Note',
 'Mode/Terms of Payment',
 'Hassan - 573201',
 'Mob : 9448919881, 7760638884',
 'GSTIN/UIN: 29AFHPM3915J1Z5',
 'Reference No. & Date.',
 'Other References',
 'State Name : Kamataka, Code : 29',
 'Buyer (Bill to)',
 "Buyer's Order No.",
 'Dated',
 'MCE CES',
 'Malnad College of Engineering',
 'Dispatch Doc No',
 'Delivery Note Date',
 'Salagame Rd, Rangoli Halla',
 'Hassan',
 'Dispatched through',
 'Destination',
 'State Name',
 ': Karnataka, Code : 29',
 'Terms of Delivery',
 'SI',
 'Description of Goods',
 'HSN/SAC',
 'GST',
 'Quantity',
 'Rate',
 'Rate',
 'per',
 'Amount',
 'No.',
 'Rate',
 '..',
 '(Incl. of Tax)',
 '1',
 'Casio FX 991 ES Plus Calculator',
 '84701000',
 '18 %',
 '50 Pcs',
 '1,225.01',
 '1,038.14',
 'Pcs',
 '51,907.00',
 '2',
 'Omega Roller Scale 16cms',
 '90172010',
 '18 %',
 '160 Pcs',
 '38.00

In [54]:
pprint.pprint(len(result[0]["rec_polys"]))
pprint.pprint(result[0]["rec_polys"])

147
[array([[82, 15],
       ...,
       [82, 59]], shape=(4, 2), dtype=int16),
 array([[1264,   11],
       ...,
       [1265,   52]], shape=(4, 2), dtype=int16),
 array([[1529,    7],
       ...,
       [1530,   53]], shape=(4, 2), dtype=int16),
 array([[1751,    6],
       ...,
       [1752,   45]], shape=(4, 2), dtype=int16),
 array([[ 82,  65],
       ...,
       [ 82, 109]], shape=(4, 2), dtype=int16),
 array([[1265,   63],
       ...,
       [1266,  104]], shape=(4, 2), dtype=int16),
 array([[1752,   57],
       ...,
       [1753,  103]], shape=(4, 2), dtype=int16),
 array([[1268,  110],
       ...,
       [1269,  148]], shape=(4, 2), dtype=int16),
 array([[1756,  103],
       ...,
       [1756,  144]], shape=(4, 2), dtype=int16),
 array([[ 86, 114],
       ...,
       [ 86, 148]], shape=(4, 2), dtype=int16),
 array([[ 82, 154],
       ...,
       [ 82, 194]], shape=(4, 2), dtype=int16),
 array([[ 84, 198],
       ...,
       [ 84, 236]], shape=(4, 2), dtype=int16),
 array([[127

In [84]:
pprint.pprint(result[0]["rec_texts"][0])
pprint.pprint(result[0]["rec_polys"][0])

print(result[0]["rec_polys"][0][:])
poly=result[0]["rec_polys"][0][:]

'PARMESHWARA STATIONERY'
array([[82, 15],
       ...,
       [82, 59]], shape=(4, 2), dtype=int16)
[[82 15]
 ...
 [82 59]]


In [83]:
# to get the max and min points 
def getMinMaxPoint(poly):
    x0 = int(poly[:,0].min())
    y0 = int(poly[:,1].min())
    x1 = int(poly[:,0].max())
    y1 = int(poly[:,1].max())
    return [x0, y0, x1, y1] 

print(getMinMaxPoint(poly))
 # the rectangle for the **entire line**


[82, 15, 675, 66]


In [101]:
pprint.pprint(result[0]["rec_texts"][0].split())
a=result[0]["rec_texts"][0].split()

print(len(a[0].strip()))

print(result[0]["rec_texts"][0])
print(len(result[0]["rec_texts"][0]))
print(len(a[0]),len(a[1]))

['PARMESHWARA', 'STATIONERY']
11
PARMESHWARA STATIONERY
22
11 10


In [117]:
xy_points=getMinMaxPoint(poly)
sentence = result[0]["rec_texts"][0].split()

letter_width=(xy_points[2]-xy_points[1])/len(text)


def tokenize_sent (xy_points,sentence,letter_width):
    print(xy_points,text,letter_width)
    for text 
    

tokenize_sent(xy_points,text,letter_width)

# word_box[]
# num_words=len(result[0]["rec_texts"][0])

hi
[82, 15, 675, 66] ['PARMESHWARA', 'STATIONERY'] 330.0
