In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from LLMParser import *
from OCREngine import *
from OCRStructureAnalyzer import *
from Rotation_correction import *

D:\Anuj_S_Jain\Data\Code\Project\Society_MCE_QT\Society_MCE\Prototype\.venv\lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.3.0)/charset_normalizer (3.4.6) doesn't match a supported version!
  warnings.warn(
D:\Anuj_S_Jain\Data\Code\Project\Society_MCE_QT\Society_MCE\Prototype\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Checking connectivity to the model hosters, this may take a while. To bypass this check, set `DISABLE_MODEL_SOURCE_CHECK` to `True`.
D:\Anuj_S_Jain\Data\Code\Project\Society_MCE_QT\Society_MCE\Prototype\.venv\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py:718: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccac

In [4]:
llm = LLMParser()

llama_context: n_ctx_seq (2048) < n_ctx_train (131072) -- the full capacity of the model will not be utilized


In [5]:
ocr = OCREngine()

Creating model: ('PP-OCRv5_server_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Anuj S Jain\.paddlex\official_models\PP-OCRv5_server_det`.
Creating model: ('en_PP-OCRv5_mobile_rec', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Anuj S Jain\.paddlex\official_models\en_PP-OCRv5_mobile_rec`.


In [6]:
i="4"
image_path = f"D:/Anuj_S_Jain/Data/Code/Project/Society_MCE_QT/Society_MCE/Prototype/training data/diff_img/{i}.jpg"
image_path

'D:/Anuj_S_Jain/Data/Code/Project/Society_MCE_QT/Society_MCE/Prototype/training data/diff_img/4.jpg'

In [7]:
img = rotation_correct_img(image_path)

In [8]:
ocrResult=ocr.run_ocr(img,image_path)

In [9]:
ocrResult[0]['rec_texts']

['SI',
 'Description of Goods',
 'Quantity',
 'Rate',
 'per',
 'Amount',
 'No.',
 '1',
 'Books',
 '5,000 Nos',
 '38.00',
 'Nos',
 '1,90,000.00',
 'Record Book',
 'Size-1/4th Pages-4+96',
 'Cover-300gsm Duplex Board',
 'With Multicolor Printing',
 '& Matt Lamination',
 'Inner 60gsm Maplitho',
 'Single Color Printing',
 'Finishing-Perfect Binding',
 '2',
 'Books',
 '2,500 Nos',
 '52.00',
 'Nos',
 '1,30,000.00',
 'Record Book',
 'Size-1/4th Pages-4+144',
 'Cover 300gsm Dup',
 'Board',
 'With Multicolor Printing',
 '& Matt Lamination',
 'Inner-6Ogsm Maplitho Single',
 'Color Printing',
 '3,20,000.00',
 'CGST (Output) 9%',
 '99',
 '',
 '28,800.00',
 'SGST (Output) 9%',
 'con Bu',
 '28,800.00',
 '415342',
 'Oul0226',
 'Total',
 '7,500 Nos',
 '3,77,600.00',
 'Amount Chargeable (in words)',
 'E. &O.E',
 'INR Three Lakh Seventy Seven Thousand Six Hundred Only',
 'HSN/SAC',
 'Taxable',
 'Central Tax',
 'State Tax',
 'Total']

In [10]:
ocrResultDS=ocr.downscaling_poly_ocr_result(ocrResult)

In [37]:
ocrResultDS

[(array([[55, 26],
         ...,
         [55, 50]], shape=(4, 2), dtype=int16),
  'SI',
  0.9980632662773132),
 (array([[554,  32],
         ...,
         [554,  53]], shape=(4, 2), dtype=int16),
  'Description of Goods',
  0.9936921000480652),
 (array([[1302,   39],
         ...,
         [1302,   62]], shape=(4, 2), dtype=int16),
  'Quantity',
  0.9999328851699829),
 (array([[1495,   40],
         ...,
         [1495,   62]], shape=(4, 2), dtype=int16),
  'Rate',
  0.9997807741165161),
 (array([[1624,   44],
         ...,
         [1624,   66]], shape=(4, 2), dtype=int16),
  'per',
  0.9999089241027832),
 (array([[1752,   41],
         ...,
         [1752,   62]], shape=(4, 2), dtype=int16),
  'Amount',
  0.9999166131019592),
 (array([[53, 62],
         ...,
         [53, 86]], shape=(4, 2), dtype=int16),
  'No.',
  0.9965193271636963),
 (array([[ 55, 119],
         ...,
         [ 55, 140]], shape=(4, 2), dtype=int16),
  '1',
  0.9997742772102356),
 (array([[107, 120],
         ...

In [11]:
analyszer = OCRUtils()

In [35]:
ocr_v_group_poly,ocr_v_group_text=analyszer.group_ocr_into_lines_v(ocrResultDS,3)

(np.float64(69.0), np.float64(38.0))
SI
Description of Goods
Quantity
Amount
Rate
per
No.
1
Books
38.00
Nos
5,000 Nos
1,90,000.00
Record Book
Size-1/4th Pages-4+96
Cover-300gsm Duplex Board
With Multicolor Printing
& Matt Lamination
Inner 60gsm Maplitho
Single Color Printing
Finishing-Perfect Binding
2
Books
52.00
Nos
2,500 Nos
1,30,000.00
Record Book
Size-1/4th Pages-4+144
Cover 300gsm Dup
Board
With Multicolor Printing
& Matt Lamination
Inner-6Ogsm Maplitho Single
Color Printing
3,20,000.00
CGST (Output) 9%
28,800.00
con Bu
99

SGST (Output) 9%
28,800.00
415342
Oul0226
Total
7,500 Nos
3,77,600.00
E. &O.E
Amount Chargeable (in words)
INR Three Lakh Seventy Seven Thousand Six Hundred Only
Central Tax
Taxable
State Tax
Total
HSN/SAC


In [36]:
ocr_v_group_text

[['SI', 'Description of Goods', 'Quantity', 'Amount', 'Rate', 'per', 'No.'],
 ['1', 'Books', '38.00', 'Nos', '5,000 Nos', '1,90,000.00'],
 ['Record Book'],
 ['Size-1/4th Pages-4+96'],
 ['Cover-300gsm Duplex Board'],
 ['With Multicolor Printing'],
 ['& Matt Lamination'],
 ['Inner 60gsm Maplitho'],
 ['Single Color Printing'],
 ['Finishing-Perfect Binding'],
 ['2', 'Books', '52.00', 'Nos', '2,500 Nos', '1,30,000.00'],
 ['Record Book'],
 ['Size-1/4th Pages-4+144'],
 ['Cover 300gsm Dup', 'Board'],
 ['With Multicolor Printing'],
 ['& Matt Lamination'],
 ['Inner-6Ogsm Maplitho Single'],
 ['Color Printing'],
 ['3,20,000.00'],
 ['CGST (Output) 9%', '28,800.00'],
 ['SGST (Output) 9%', '28,800.00', '415342'],
 ['Total', '7,500 Nos', '3,77,600.00'],
 ['E. &O.E', 'Amount Chargeable (in words)'],
 ['INR Three Lakh Seventy Seven Thousand Six Hundred Only'],
 ['Central Tax', 'Taxable', 'State Tax', 'Total', 'HSN/SAC']]

In [20]:
ocr_v_group_text

[['SI', 'Description of Goods', 'Quantity', 'Amount', 'Rate', 'per', 'No.'],
 ['1', 'Books', '38.00', 'Nos', '5,000 Nos', '1,90,000.00', 'Record Book'],
 ['Size-1/4th Pages-4+96'],
 ['Cover-300gsm Duplex Board'],
 ['With Multicolor Printing'],
 ['& Matt Lamination'],
 ['Inner 60gsm Maplitho'],
 ['Single Color Printing'],
 ['Finishing-Perfect Binding'],
 ['2', 'Books', '52.00', 'Nos', '2,500 Nos', '1,30,000.00'],
 ['Record Book'],
 ['Size-1/4th Pages-4+144'],
 ['Cover 300gsm Dup', 'Board'],
 ['With Multicolor Printing'],
 ['& Matt Lamination'],
 ['Inner-6Ogsm Maplitho Single'],
 ['Color Printing'],
 ['3,20,000.00'],
 ['CGST (Output) 9%', '28,800.00'],
 ['SGST (Output) 9%', '28,800.00', '415342'],
 ['Total', '7,500 Nos', '3,77,600.00'],
 ['E. &O.E', 'Amount Chargeable (in words)'],
 ['INR Three Lakh Seventy Seven Thousand Six Hundred Only'],
 ['Central Tax', 'Taxable', 'State Tax', 'Total', 'HSN/SAC']]

In [23]:
colNumber=analyszer.get_heading_col(7,ocr_v_group_text)

In [24]:
colNumber

['SI', 'Description of Goods', 'Quantity', 'Amount', 'Rate', 'per', 'No.']