# display version of python

In [1]:
!py --version

Python 3.10.8


# import the libary

In [2]:
from paddleocr import PaddleOCR 
import paddle
import cv2
import numpy as np

D:\Anuj_S_Jain\Data\Code\Project\Society_MCE_QT\Society_MCE\Prototype\.venv\lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.3.0)/charset_normalizer (3.4.6) doesn't match a supported version!
  warnings.warn(
D:\Anuj_S_Jain\Data\Code\Project\Society_MCE_QT\Society_MCE\Prototype\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Checking connectivity to the model hosters, this may take a while. To bypass this check, set `DISABLE_MODEL_SOURCE_CHECK` to `True`.
D:\Anuj_S_Jain\Data\Code\Project\Society_MCE_QT\Society_MCE\Prototype\.venv\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py:718: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccac

In [3]:
import paddle
print(paddle.device.get_device())

cpu


# loading image path

In [4]:
image_path1 = "./training data/diff pattren img/2.jpg"
image_path2 = "./training data/diff pattren img/2.jpeg"

# convert the image to bgr to rgb

In [5]:
# Load the image
image1 = cv2.imread(image_path1)
# Convert to grayscale
gray_image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2RGB)


# Load the image
image2 = cv2.imread(image_path2)
# Convert to grayscale
gray_image2 = cv2.cvtColor(image2, cv2.COLOR_BGR2RGB)

#### convert the image to black and white

In [6]:
# ret1,bw_img1 = cv2.threshold(gray_image1, 127, 255, cv2.THRESH_BINARY)
# ret2,bw_img2 = cv2.threshold(gray_image2, 127, 255, cv2.THRESH_BINARY)
#ret are the threshold value used 

#### ref for resize

In [7]:
#cv2.resize(img, (800, 600))
# cv2.resize(image1, (800, 600))
# cv2.resize(image2, (800, 600))

# cv2.resize(gray_image1, (800, 600))
# cv2.resize(gray_image2, (800, 600))

# cv2.resize(bw_img1, (800, 600))
# cv2.resize(bw_img2, (800, 600))

# display all the img

In [8]:
# Show the image in a window
# cv2.imshow('image1', cv2.resize(image1, (800, 600)))
# cv2.imshow('image2', cv2.resize(image2, (800, 600)))

# cv2.imshow('gray_image1', cv2.resize(gray_image1, (800, 600)))
# cv2.imshow('gray_image2', cv2.resize(gray_image2, (800, 600)))

# cv2.imshow('bw_img1', cv2.resize(bw_img1, (800, 600)))
# cv2.imshow('bw_img2', cv2.resize(bw_img2, (800, 600)))


# run paddleocr on img 

In [9]:
print(paddle.device.get_device())
image_path1="./training data/diff pattren img/2.jpg"
img = cv2.imread(image_path1)
import os
print(img is None)
os.environ["OMP_NUM_THREADS"] = "8"
os.environ["MKL_NUM_THREADS"] = "8"

ocr = PaddleOCR(use_doc_orientation_classify=False, 
    use_doc_unwarping=False, 
    use_textline_orientation=False,
    lang='en',
    device='cpu',
    cpu_threads=8 
   )
# result1 = ocr.predict(gray_image1)
result1 = ocr.predict(img)

Creating model: ('PP-OCRv5_server_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Anuj S Jain\.paddlex\official_models\PP-OCRv5_server_det`.


cpu
False


Creating model: ('en_PP-OCRv5_mobile_rec', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Anuj S Jain\.paddlex\official_models\en_PP-OCRv5_mobile_rec`.


In [10]:
result1

[{'input_path': None,
  'page_index': None,
  'doc_preprocessor_res': {'output_img': array([[[254, ..., 254],
           ...,
           [ 19, ...,  38]],
   
          ...,
   
          [[ 81, ...,  81],
           ...,
           [  1, ...,  16]]], shape=(3300, 2284, 3), dtype=uint8)},
  'dt_polys': [array([[496,  38],
          ...,
          [497, 117]], shape=(4, 2), dtype=int16),
   array([[933,  54],
          ...,
          [930,  96]], shape=(4, 2), dtype=int16),
   array([[1145,   64],
          ...,
          [1139,  143]], shape=(4, 2), dtype=int16),
   array([[1506,   70],
          ...,
          [1505,  104]], shape=(4, 2), dtype=int16),
   array([[962,  97],
          ...,
          [959, 133]], shape=(4, 2), dtype=int16),
   array([[160, 156],
          ...,
          [159, 193]], shape=(4, 2), dtype=int16),
   array([[1179,  177],
          ...,
          [1178,  208]], shape=(4, 2), dtype=int16),
   array([[119, 193],
          ...,
          [118, 223]], shape=(4, 

In [11]:
# print(paddle.device.get_device())
# ocr = PaddleOCR(use_textline_orientation=True, lang='en', device='gpu')
# result2 = ocr.predict(gray_image1)

In [12]:
# result2

In [13]:
 print(result1[0]["rec_polys"][0][0])
 print(result1[0]["rec_polys"][0][1])
 print(result1[0]["rec_polys"][0][2])
 print(result1[0]["rec_polys"][0][3])


[496  38]
[713  36]
[714 115]
[497 117]


In [14]:
# # (790, 1119)
# # point=(496  ,23)
# image1 = cv2.imread(image_path1)
# img_copy=image1.copy()
# # cv2.circle(img_copy, point, radius=4, color=(0, 0, 255), thickness=2)
# cv2.fillPoly(img_copy, [np.array(result1[0]["rec_polys"][0], dtype=np.int32)], (255, 255, 255))
# # cv2.polylines(img_copy,[np.array(result1[0]["rec_polys"][0], dtype=np.int32)], isClosed=True, color=(0, 255, 0), thickness=1)
# cv2.imwrite('./output/opencv/imagetry.jpeg', img_copy)
# # cv2.circle(image, point, radius=3, color=(0, 0, 255), thickness=-1)
# # cv2.circle(image, point, radius=3, color=(0, 0, 255), thickness=-1)
# # cv2.circle(image, point, radius=3, color=(0, 0, 255), thickness=-1)

In [13]:
import cv2
import numpy as np
image_path1="./training data/diff pattren img/2.jpg"
img = cv2.imread(image_path1)

if img is None:
    print("Image not loaded. Check path!")

# # Convert to binary (important!)
# _, binary = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

# # Create kernel (controls thickness)
# kernel = np.ones((5, 5), np.uint8)

# # Apply dilation
# thick = cv2.dilate(binary, kernel, iterations=1)

#----------------------------------
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# largest_contour = max(contours, key=cv2.contourArea)
# cv2.drawContours(img, largest_contour, -1, (0,255,0), 4)
# cv2.imwrite('./output/opencv/img.jpeg', img)
# print(largest_contour)
# contours, _ = cv2.findContours(gray, cv2.RETR_REC, cv2.CHAIN_APPROX_SIMPLE)
# cv2.drawContours(gray, contours, -1, (0,255,0), 4)

cv2.imwrite('./output/opencv/gray1.jpeg', gray)


clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
gray = clahe.apply(gray)

cv2.imwrite('./output/opencv/gray2.jpeg', gray)

# ✅ Better threshold (adaptive handles uneven lighting)
thresh = cv2.adaptiveThreshold(
    gray, 255,
    cv2.ADAPTIVE_THRESH_MEAN_C,
    cv2.THRESH_BINARY_INV,
    15, 2
)

kernel = np.zeros((3,3), np.uint8)
thresh = cv2.erode(thresh, kernel, iterations=4)

cv2.imwrite('./output/opencv/thresh1.jpeg', thresh)


# --- Horizontal lines ---
horizontal_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (60,1))
horizontal = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, horizontal_kernel)
cv2.imwrite('./output/opencv/horizontal.jpeg', horizontal)
# 🔥 connect broken horizontal lines
horizontal = cv2.dilate(horizontal, np.ones((3,3),np.uint8), iterations=2)
cv2.imwrite('./output/opencv/horizontal1.jpeg', horizontal)
# --- Vertical lines ---
vertical_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (1,60))
vertical = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, vertical_kernel)
cv2.imwrite('./output/opencv/vertical.jpeg', vertical)
# 🔥 connect broken vertical lines
vertical = cv2.dilate(vertical, np.ones((3,3),np.uint8), iterations=2)
cv2.imwrite('./output/opencv/vertical1.jpeg', vertical)
# Combine
boxes = cv2.add(horizontal, vertical)
cv2.imwrite('./output/opencv/boxes.jpeg', boxes)
# 🔥 Final closing to join gaps
kernel = np.ones((10,10), np.uint8)
boxes = cv2.morphologyEx(boxes, cv2.MORPH_CLOSE, kernel, iterations=2)
cv2.imwrite('./output/opencv/boxes1.jpeg', boxes)




# kernel = np.ones((3,6), np.uint8)
# dilated = cv2.dilate(boxes, kernel, iterations=2)
# cv2.imwrite('./output/opencv/boxes4.jpeg', dilated)
#make the img border small
# Define a kernel (3x3)
kernel = np.ones((3,3), np.uint8)
# Apply erosion
eroded = cv2.erode(boxes, kernel, iterations=1)
cv2.imwrite('./output/opencv/boxes2.jpeg', eroded)

# Find contours
contours, _ = cv2.findContours(boxes, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
# cv2.imwrite('./output/opencv/contours.jpeg', contours)

output = img.copy()

image_out = cv2.imread('./output/opencv/boxes1.jpeg')

cv2.drawContours(output, contours, -1, (0,255,0), 1)
# for cnt in contours:
    # x,y,w,h = cv2.boundingRect(cnt)
    # cv2.line(image_out, cnt[0], cnt[1], (0, 255, 0), 2)
    # filter noise
    # if w > 40 and h > 20:
    # cv2.rectangle(image_out, (x,y), (x+w,y+h), (0,255,255), 2)
cv2.imwrite('./output/opencv/output.jpeg', output)
# cv2.imshow("Fixed Boxes", output)
# cv2.waitKey(0)

True

In [ ]:
image1 = cv2.imread(image_path1)
img_copy=image1.copy()

img_copy_gray = cv2.cvtColor(img_copy, cv2.COLOR_BGR2GRAY)

horizontal_kernel = (80,1)
vertical_kernel = (1,80)
boxes = cv2.add(horizontal_kernel, vertical_kernel)

kernel = np.ones((5,5), np.uint8)
boxes = cv2.morphologyEx(img_copy_gray, cv2.MORPH_CLOSE, kernel, iterations=2)

img_copy_gray = cv2.equalizeHist(boxes)
edges = cv2.Canny(img_copy_gray, threshold1=00, threshold2=200)
# _,img_copy_bw = cv2.threshold(img_copy_gray, 127, 255, cv2.THRESH_BINARY)
# Binary image (invert so lines = white)
_, img_copy_bw = cv2.threshold(img_copy_gray, 200, 255, cv2.THRESH_BINARY_INV)
contours, _ = cv2.findContours(img_copy_bw, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
print(contours)
cv2.drawContours(image1, contours, -1, (0,255,255), 4)
# edges = cv2.Canny(img_copy, threshold1=50, threshold2=200)
# _,img_copy = cv2.threshold(img_copy, 127, 255, cv2.THRESH_BINARY)
# kernel = np.ones((2, 2), np.uint8)
# img_copy = cv2.erode(img_copy, kernel, iterations=6)
# cv2.imwrite('./output/opencv/imagetry.jpeg', img_copy)


cv2.imwrite('./output/opencv/imagetry.jpeg', image1)

In [38]:
# shrink_factor_h = 0.90
# shrink_factor_v = 0.50

# w = x_max - x_min
# h = y_max - y_min

# # adaptive shrink
# shrink_factor_h = max(0.6, min(0.9, 1 - 20/w))
# shrink_factor_v = max(0.6, min(0.9, 1 - 20/h))

new_poly = []
for poly in result1[0]["rec_polys"]:
    # convert to float for calculation
    poly = np.array(poly, dtype=np.float32)

    
    x_min, y_min = np.min(poly, axis=0)
    x_max, y_max = np.max(poly, axis=0)

    w = x_max - x_min
    h = y_max - y_min

    # adaptive shrink
    shrink_factor_h = max(0.6, min(0.9, 1 - 20/w))
    shrink_factor_v = max(0.6, min(0.9, 1 - 20/h))
    # print(poly)
    # compute center
    center_x = np.mean(poly[:, 0])
    center_y = np.mean(poly[:, 1])
    # print(center_x)
    poly_box=[]
    for (x,y) in poly:
        # print(x,y)
        x_new=center_x+(x-center_x)*shrink_factor_h
        y_new=center_y+(y-center_y)*shrink_factor_v
        poly_box.append([x_new,y_new])
    cv2.polylines(output, [np.array(poly_box, dtype=np.int32)],isClosed=True, color=(0, 255, 255),thickness=1)
    # cv2.polylines(imagetry,[box1] , isClosed=True, color=(0,255,0), thickness=2)
    # print(poly_box)
    new_poly.append(poly_box)
    
    # for i in poly:
        # print(i)
        # new_x = x + (center_x - x) * shrink_factor
        # new_y = y + (center_y - y) * shrink_factor
        # new_poly.append([int(new_x), int(new_y)])
        # pts = np.array(new_poly, dtype=np.int32).reshape((-1, 1, 2))
    # fill white
# cv2.fillPoly(img_copy, [np.array(new_poly[0], dtype=np.int32)], (255, 255, 255))
# kernel = np.ones((5, 5), np.uint8)
# img_copy = cv2.erode(img_copy, kernel, iterations=-9)
cv2.imwrite('./output/opencv/imagetry.jpeg', output)
new_poly[0]

[[np.float32(506.9), np.float32(47.506172)],
 [np.float32(702.2), np.float32(46.0)],
 [np.float32(703.1), np.float32(105.49383)],
 [np.float32(507.8), np.float32(107.0)]]

In [ ]:
from PIL import Image
image = Image.open(image_path1).convert("RGB")
width, height = image.size
image.size

In [ ]:
# imagetry = cv2.imread(image_path1)
# import numpy as np
# for line in result1[0]["rec_polys"]:
#     box = line
#     box = [(int(x), int(y)) for x, y in box]

#     # Draw bounding box
#     cv2.polylines(imagetry,[np.array(result1[0]["rec_polys"][0], dtype=np.int32)], isClosed=True, color=(0, 255, 0), thickness=2)
#     cv2.imwrite('./output/opencv/imagetry.jpeg', imagetry)

In [12]:
# import cv2

# # Load image
# # image_path_c="./training data/diff pattren img/1.jpg
# image_path_c="./output/opencv/cropped.jpg"
# image = cv2.imread(image_path_c)
# original = image.copy()

# # Convert to grayscale
# gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# # Blur (optional but helps)
# blur = cv2.GaussianBlur(gray, (5, 5), 0)

# # Threshold
# _, thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

# # Find contours (external only)
# contours, _ = cv2.findContours(
#     thresh, 
#     cv2.RETR_LIST,   # 👈 only outer border
#     cv2.CHAIN_APPROX_SIMPLE
# )
# org=cv2.drawContours(original, contours, -1, (0,255,0), 4)
# cv2.imwrite("./output/opencv/cropped.jpg", org)
# # Get largest contour
# largest_contour = max(contours, key=cv2.contourArea)

# # Bounding box
# x, y, w, h = cv2.boundingRect(largest_contour)

# # Crop
# cropped = original[y:y+h, x:x+w]

# # Save or display
# # cv2.imwrite("./output/opencv/cropped.jpg", cropped)

In [7]:
contours

(array([[[   5,    0]],
 
        [[   5,    6]],
 
        [[   6,    7]],
 
        [[   6,   26]],
 
        [[   5,   27]],
 
        [[   5,   49]],
 
        [[   6,   50]],
 
        [[   6,   53]],
 
        [[   5,   54]],
 
        [[   5,   70]],
 
        [[   6,   71]],
 
        [[   6,   88]],
 
        [[   5,   89]],
 
        [[   5,   92]],
 
        [[   6,   93]],
 
        [[   6,   96]],
 
        [[   5,   97]],
 
        [[   5,  159]],
 
        [[   6,  160]],
 
        [[   6,  175]],
 
        [[   5,  176]],
 
        [[   5,  205]],
 
        [[   6,  206]],
 
        [[   6,  215]],
 
        [[   5,  216]],
 
        [[   5,  260]],
 
        [[   4,  261]],
 
        [[   4,  286]],
 
        [[   3,  287]],
 
        [[   3,  295]],
 
        [[   4,  296]],
 
        [[   4,  309]],
 
        [[   3,  310]],
 
        [[   3,  376]],
 
        [[   2,  377]],
 
        [[   2,  466]],
 
        [[   1,  467]],
 
        [[   1,  484]],
 
        [[  

In [ ]:
# import numpy as np
# # box1 = np.array([[307 ,  2], [496 ,  0], [497 , 17], [307 , 22]], dtype=np.int32)
# imagetry = cv2.imread(image_path1)
# # box1 = np.array([[307 ,  2], [496 ,  0], [497 , 17], [307 , 22]], dtype=np.int32)
# box1 = np.array(result1[0]["rec_polys"][0], dtype=np.int32)
# # cv2.polylines(imagetry,[box1] , isClosed=True, color=(0,255,0), thickness=2)
# # cv2.drawContours(imagetry,[[307 ,  2], [496 ,  0], [497 , 17], [307 , 22]], -1, (255, 255, 0), 1 )
# # cv2.imwrite('./output/opencv/imagetry.jpeg', imagetry)

In [ ]:
# for line in result1[0]["rec_polys"]:
#     # Convert to integer points
#     pts = np.array(line, dtype=np.int32)
#     # Draw filled white polygon over text
#     cv2.fillPoly(image1, [pts], (255, 255, 255))
# # Save result
# cv2.imwrite('./output/opencv/output.jpg', image1)

In [ ]:
# cv2.imshow("Box", image1)
# cv2.imwrite('./output/opencv/Box.jpeg', image1)

In [ ]:
# # Load the image
# image1 = cv2.imread(image_path1)
# # Convert to grayscale
# gray_image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
# _, bw_image = cv2.threshold(gray_image1, 127, 255, cv2.THRESH_BINARY)
# # kernel = np.ones((5, 1), np.uint8)
# # img_erosion = cv2.erode(bw_image, kernel, iterations=-9)
# # blurred = cv2.GaussianBlur(bw_image, (15, 15), 0)

# contours, her = cv2.findContours(bw_image.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
# print(len(contours))
# cv2.drawContours(image1, contours, -1, (0, 255, 0), 1 )
# cv2.imwrite('./output/opencv/image1.jpeg', image1)